"use client";
import Link from "next/link";
import { useEffect, useState, useTransition } from "react";

type Pending = { id: string; nombre_operacion: string; placa: string; fecha: string; conductor: string | null; empresa_transportadora: string | null; estado_inspeccion: string; estado_cargue: string };
export function AdminCierreSalidasPanel() {
  const [items, setItems] = useState<Pending[]>([]); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const load = async () => { const response = await fetch("/api/admin/cierre-salidas", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result); };
  useEffect(() => { fetch("/api/admin/cierre-salidas", { cache: "no-store" }).then(async (r) => { const result = await r.json(); if (!r.ok) throw new Error(result.error); return result as Pending[]; }).then(setItems).catch((reason) => setError(reason.message)); }, []);
  function close(item: Pending) { if (!window.confirm(`¿Cerrar administrativamente la salida de ${item.placa}? Esta acción quedará registrada en Auditoría.`)) return; setError(null); setMessage(null); startTransition(async () => { try { const response = await fetch("/api/admin/cierre-salidas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nombreOperacion: item.nombre_operacion }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage(`Salida de ${item.placa} cerrada administrativamente.`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible cerrar la salida."); } }); }
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-7xl space-y-7 px-6 py-10"><header className="rounded-[2rem] bg-white p-8 shadow-lg"><div className="flex justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.25em] text-rose-700">Solo administradores</span><h1 className="mt-3 text-4xl font-semibold">Cierre administrativo de salidas</h1><p className="mt-3 max-w-3xl text-slate-600">Cierra operaciones cuyo F-SU-04 no fue diligenciado. Se guardará sin fotografías y quedará identificado en Auditoría.</p></div><Link href="/" className="h-fit rounded-2xl border px-4 py-3 text-sm font-semibold">Volver</Link></div></header>{message ? <p className="rounded-2xl bg-emerald-50 p-4 text-emerald-800">{message}</p> : null}{error ? <p className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p> : null}<section className="overflow-hidden rounded-[2rem] border bg-white shadow-lg"><div className="border-b p-6"><h2 className="text-xl font-semibold">Operaciones con salida pendiente</h2><p className="mt-1 text-sm text-slate-600">Revisa cuidadosamente la operación antes de cerrarla.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Placa</th><th className="p-4">Fecha</th><th className="p-4">Conductor</th><th className="p-4">Transportadora</th><th className="p-4">Inspección</th><th className="p-4">Cargue</th><th className="p-4 text-right">Acción</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="p-4 font-semibold">{item.placa}</td><td className="p-4">{item.fecha}</td><td className="p-4">{item.conductor || "Sin registrar"}</td><td className="p-4">{item.empresa_transportadora || "Sin registrar"}</td><td className="p-4">{item.estado_inspeccion}</td><td className="p-4">{item.estado_cargue}</td><td className="p-4 text-right"><button type="button" disabled={pending} onClick={() => close(item)} className="rounded-xl bg-rose-700 px-4 py-2 font-semibold text-white disabled:bg-slate-400">Cerrar salida</button></td></tr>)}{!items.length ? <tr><td colSpan={7} className="p-8 text-center text-slate-500">No hay operaciones con salida pendiente.</td></tr> : null}</tbody></table></div></section></main></div>;
}
