"use client";
import Link from "next/link";
import { EliminarEmbarqueButton } from "@/components/eliminar-embarque-button";
import { useEffect, useState, useTransition } from "react";
import { InputField } from "@/components/form-ui";
import type { EmbarqueKit } from "@/lib/trazabilidad-kits";

export function EmbarquesForm({ isAdmin = false }: { isAdmin?: boolean }) {
  const [numeroEmbarque, setNumeroEmbarque] = useState(""); const [numeroKit, setNumeroKit] = useState(""); const [observaciones, setObservaciones] = useState("");
  const [records, setRecords] = useState<EmbarqueKit[]>([]); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const load = async () => { const response = await fetch("/api/embarques", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setRecords(result); };
  useEffect(() => {
    fetch("/api/embarques", { cache: "no-store" })
      .then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); return result as EmbarqueKit[]; })
      .then(setRecords)
      .catch((reason) => setError(reason instanceof Error ? reason.message : "No fue posible consultar embarques."));
  }, []);
  function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); startTransition(async () => { try { const response = await fetch("/api/embarques", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ numeroEmbarque, numeroKit, observaciones }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setNumeroEmbarque(""); setNumeroKit(""); setObservaciones(""); setMessage("Embarque creado y kit asignado correctamente."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible crear el embarque."); } }); }
  return <Page title="Creación de embarques" subtitle="Auxiliar de Comercio asigna un kit cerrado a cada embarque."><form onSubmit={submit} className="space-y-5 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-lg md:p-8"><div className="grid gap-4 md:grid-cols-2"><InputField label="Número de embarque" value={numeroEmbarque} onChange={setNumeroEmbarque} required /><InputField label="Número del kit" value={numeroKit} onChange={setNumeroKit} required /></div><label className="flex flex-col gap-2 text-sm font-medium text-slate-700">Observaciones<textarea rows={3} value={observaciones} onChange={(e) => setObservaciones(e.target.value)} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3" /></label><button disabled={pending} className="w-full rounded-2xl bg-slate-950 px-5 py-4 font-semibold text-white disabled:bg-slate-400">{pending ? "Guardando..." : "Crear embarque y asignar kit"}</button><Notice message={message} error={error} /></form><section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-lg"><div className="border-b p-6"><h2 className="text-xl font-semibold">Trazabilidad de embarques</h2><p className="mt-1 text-sm text-slate-600">Creación, recepción en Portería y salida hacia Logística.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Embarque</th><th className="p-4">Kit</th><th className="p-4">Estado</th><th className="p-4">Creado</th><th className="p-4">Entrada a Portería</th><th className="p-4">Salida a Logística</th>{isAdmin ? <th className="p-4">Acciones</th> : null}</tr></thead><tbody className="divide-y">{records.map((item) => <tr key={item.id}><td className="p-4 font-semibold">{item.numero_embarque}</td><td className="p-4">{item.numero_kit}</td><td className="p-4">{stateLabel(item.estado)}</td><td className="p-4">{formatDateTime(item.created_at)}</td><td className="p-4">{formatDateTime(movementDate(item.precintos_recepciones))}</td><td className="p-4">{formatDateTime(movementDate(item.precintos_despachos))}</td>{isAdmin ? <td className="p-4"><EliminarEmbarqueButton embarque={item} onDeleted={(id) => { setRecords((current) => current.filter((row) => row.id !== id)); setError(null); setMessage("Embarque eliminado. El motivo y el historial quedaron registrados."); }} /></td> : null}</tr>)}</tbody></table></div></section></Page>;
}
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-6xl space-y-7 px-6 py-10"><header className="rounded-[2rem] bg-white p-8 shadow-lg"><div className="flex justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.25em] text-emerald-700">Trazabilidad de kits</span><h1 className="mt-3 text-4xl font-semibold">{title}</h1><p className="mt-3 text-slate-600">{subtitle}</p></div><Link href="/" className="h-fit rounded-2xl border px-4 py-3 text-sm font-semibold">Volver</Link></div></header>{children}</main></div>; }
function Notice({ message, error }: { message: string | null; error: string | null }) { return <>{message ? <p className="rounded-2xl bg-emerald-50 p-4 text-emerald-800">{message}</p> : null}{error ? <p className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p> : null}</>; }
function stateLabel(value: string) { return ({ PENDIENTE_RECEPCION: "Pendiente de recepción", DISPONIBLE_PORTERIA: "Disponible en portería", DESPACHADO: "Despachado", ANULADO: "Anulado" } as Record<string, string>)[value] ?? value; }
function formatDateTime(value?: string) { return value ? new Date(value).toLocaleString("es-CO", { timeZone: "America/Bogota" }) : "Pendiente"; }
function movementDate(value: { created_at: string } | { created_at: string }[] | null | undefined) { return Array.isArray(value) ? value[0]?.created_at : value?.created_at; }
