"use client";
import Link from "next/link";
import { useEffect, useMemo, useState, useTransition } from "react";
import { FileField, InputField, SelectField } from "@/components/form-ui";
import { SignaturePad } from "@/components/signature-pad";
import type { PrecintosEmpleado } from "@/lib/precintos-empleados";
import type { EmbarqueKit } from "@/lib/trazabilidad-kits";

export function PrecintosForm({ mode = "entrada" }: { mode?: "entrada" | "salida" }) {
  const salida = mode === "salida"; const requiredState = salida ? "DISPONIBLE_PORTERIA" : "PENDIENTE_RECEPCION";
  const [embarques, setEmbarques] = useState<EmbarqueKit[]>([]); const [empleados, setEmpleados] = useState<PrecintosEmpleado[]>([]);
  const [embarqueId, setEmbarqueId] = useState(""); const [unoId, setUnoId] = useState(""); const [dosId, setDosId] = useState(""); const [foto, setFoto] = useState<File | null>(null); const [firmaUno, setFirmaUno] = useState<File | null>(null); const [firmaDos, setFirmaDos] = useState<File | null>(null); const [observaciones, setObservaciones] = useState(""); const [reset, setReset] = useState(0); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const load = async () => { const [a, b] = await Promise.all([fetch(`/api/embarques?estado=${requiredState}`, { cache: "no-store" }), fetch("/api/precintos-empleados", { cache: "no-store" })]); const ar = await a.json(); const br = await b.json(); if (!a.ok) throw new Error(ar.error); if (!b.ok) throw new Error(br.error); setEmbarques(ar); setEmpleados(br); };
  useEffect(() => {
    Promise.all([fetch(`/api/embarques?estado=${requiredState}`, { cache: "no-store" }), fetch("/api/precintos-empleados", { cache: "no-store" })])
      .then(async ([a, b]) => { const ar = await a.json(); const br = await b.json(); if (!a.ok) throw new Error(ar.error); if (!b.ok) throw new Error(br.error); return [ar as EmbarqueKit[], br as PrecintosEmpleado[]] as const; })
      .then(([nextEmbarques, nextEmpleados]) => { setEmbarques(nextEmbarques); setEmpleados(nextEmpleados); })
      .catch((reason) => setError(reason instanceof Error ? reason.message : "No fue posible cargar el formulario."));
  }, [requiredState]);
  const colfrutas = useMemo(() => empleados.filter((x) => x.empresa === "COLFRUTAS"), [empleados]); const atempi = useMemo(() => empleados.filter((x) => x.empresa === "ATEMPI"), [empleados]);
  const personasUno = salida ? atempi : colfrutas; const personasDos = salida ? colfrutas : atempi; const uno = personasUno.find((x) => x.id === unoId); const dos = personasDos.find((x) => x.id === dosId); const embarque = embarques.find((x) => x.id === embarqueId);
  function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); startTransition(async () => { try { const form = new FormData(); form.set("embarqueId", embarqueId); form.set("personaUnoNombre", uno?.nombre ?? ""); form.set("personaUnoCedula", uno?.cedula ?? ""); form.set("personaDosNombre", dos?.nombre ?? ""); form.set("personaDosCedula", dos?.cedula ?? ""); form.set("observaciones", observaciones); if (foto) form.set("foto", foto); if (firmaUno) form.set("firmaUno", firmaUno); if (firmaDos) form.set("firmaDos", firmaDos); const response = await fetch(salida ? "/api/salida-precintos" : "/api/precintos", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setEmbarqueId(""); setUnoId(""); setDosId(""); setFoto(null); setFirmaUno(null); setFirmaDos(null); setObservaciones(""); setReset((x) => x + 1); setMessage(salida ? "Salida registrada correctamente." : "Recepción registrada correctamente."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible guardar."); } }); }
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-6xl space-y-7 px-6 py-10"><header className="rounded-[2rem] bg-white p-8 shadow-lg"><div className="flex justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.25em] text-emerald-700">Trazabilidad de kits</span><h1 className="mt-3 text-4xl font-semibold">{salida ? "Salida del kit" : "Entrega del kit en portería"}</h1><p className="mt-3 text-slate-600">{salida ? "Selecciona un embarque recibido, fotografía el kit y registra las firmas de Portería y Logística." : "Selecciona el embarque creado por Auxiliar de Comercio, fotografía la bolsa cerrada y registra las dos firmas."}</p></div><Link href="/" className="h-fit rounded-2xl border px-4 py-3 text-sm font-semibold">Volver</Link></div></header>
  <form onSubmit={submit} className="space-y-6 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-lg md:p-8"><SelectField label="Número de embarque" value={embarqueId} onChange={setEmbarqueId} options={embarques.map((x) => ({ value: x.id, label: x.numero_embarque }))} required tone="sky" />{embarque ? <div className="grid gap-4 rounded-2xl bg-emerald-50 p-5 md:grid-cols-2"><InputField label="Embarque seleccionado" value={embarque.numero_embarque} onChange={() => undefined} disabled /><InputField label="Kit asignado" value={embarque.numero_kit} onChange={() => undefined} disabled /></div> : null}<FileField label="Fotografía del kit cerrado" file={foto} onChange={setFoto} sourceOptions /><div className="grid gap-4 md:grid-cols-2"><SelectField label={salida ? "Persona de Portería" : "Auxiliar de Comercio"} value={unoId} onChange={setUnoId} options={personasUno.map((x) => ({ value: x.id, label: x.nombre }))} required /><SelectField label={salida ? "Persona de Logística" : "Persona de Portería"} value={dosId} onChange={setDosId} options={personasDos.map((x) => ({ value: x.id, label: x.nombre }))} required /></div><div className="grid gap-4 md:grid-cols-2"><InputField label="Cédula primera persona" value={uno?.cedula ?? ""} onChange={() => undefined} disabled /><InputField label="Cédula segunda persona" value={dos?.cedula ?? ""} onChange={() => undefined} disabled /></div><label className="flex flex-col gap-2 text-sm font-medium text-slate-700">Observaciones<textarea rows={3} value={observaciones} onChange={(e) => setObservaciones(e.target.value)} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3" /></label><div className="grid gap-5 md:grid-cols-2"><SignaturePad key={`uno-${reset}`} label={`Firma ${salida ? "Portería" : "Auxiliar de Comercio"}`} onChange={setFirmaUno} /><SignaturePad key={`dos-${reset}`} label={`Firma ${salida ? "Logística" : "Portería"}`} onChange={setFirmaDos} /></div><p className="rounded-2xl bg-sky-50 p-4 text-sm text-sky-900">La fecha y la hora se registran automáticamente al guardar.</p><button disabled={pending || !embarques.length} className="w-full rounded-2xl bg-slate-950 px-5 py-4 font-semibold text-white disabled:bg-slate-400">{pending ? "Guardando..." : salida ? "Confirmar salida" : "Confirmar recepción"}</button>{!embarques.length ? <p className="text-center text-sm text-amber-700">No hay embarques disponibles para este proceso.</p> : null}{message ? <p className="rounded-2xl bg-emerald-50 p-4 text-emerald-800">{message}</p> : null}{error ? <p className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p> : null}</form></main></div>;
}
