"use client";
import Link from "next/link";
import { SavedSelladoEventCard, type SavedSelladoEvent } from "@/components/sellado-saved-event";
import { useEffect, useMemo, useState, useTransition } from "react";
import { FileField, InputField, SelectField } from "@/components/form-ui";
import { SignaturePad } from "@/components/signature-pad";
import type { PrecintosEmpleado } from "@/lib/precintos-empleados";

type Operation={nombre_operacion:string;placa:string;fecha:string;supervision:{numero_embarque:string;estado:string;supervision_sellado_eventos:SavedSelladoEvent[]}|null};
type NewSeal={tipo:""|"correa"|"botella";numero:string;foto:File|null}; const emptySeal=():NewSeal=>({tipo:"",numero:"",foto:null});
export function SupervisionSelladoForm(){
 const[operations,setOperations]=useState<Operation[]>([]);const[employees,setEmployees]=useState<PrecintosEmpleado[]>([]);const[operationName,setOperationName]=useState("");const[shipment,setShipment]=useState("");const[count,setCount]=useState(1);const[seals,setSeals]=useState<NewSeal[]>([emptySeal()]);const[installer,setInstaller]=useState("");const[supervisor,setSupervisor]=useState("");const[notes,setNotes]=useState("");const[signatureInstaller,setSignatureInstaller]=useState<File|null>(null);const[signatureSupervisor,setSignatureSupervisor]=useState<File|null>(null);const[reset,setReset]=useState(0);const[onlyStandby,setOnlyStandby]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[pending,startTransition]=useTransition();
 const load=async()=>{const[a,b]=await Promise.all([fetch("/api/supervision-sellado",{cache:"no-store"}),fetch("/api/precintos-empleados",{cache:"no-store"})]);const ar=await a.json(),br=await b.json();if(!a.ok)throw new Error(ar.error);if(!b.ok)throw new Error(br.error);setOperations(ar);setEmployees(br);};
 useEffect(()=>{Promise.all([fetch("/api/supervision-sellado",{cache:"no-store"}),fetch("/api/precintos-empleados",{cache:"no-store"})]).then(async([a,b])=>{const ar=await a.json(),br=await b.json();if(!a.ok)throw new Error(ar.error);if(!b.ok)throw new Error(br.error);return[ar,br] as [Operation[],PrecintosEmpleado[]];}).then(([a,b])=>{setOperations(a);setEmployees(b);}).catch((reason)=>setError(reason.message));},[]);
 const selected=operations.find((x)=>x.nombre_operacion===operationName);const events=selected?.supervision?.supervision_sellado_eventos??[];const filtered=onlyStandby?operations.filter((x)=>x.supervision?.estado==="stand_by"):operations;const colfrutas=useMemo(()=>employees.filter((x)=>x.empresa==="COLFRUTAS"),[employees]);const atempi=useMemo(()=>employees.filter((x)=>x.empresa==="ATEMPI"),[employees]);
 function choose(value:string){setCount(1);setSeals([emptySeal()]);setInstaller("");setSupervisor("");setNotes("");setSignatureInstaller(null);setSignatureSupervisor(null);setReset((x)=>x+1);setError(null);setMessage(null);setOperationName(value);const op=operations.find((x)=>x.nombre_operacion===value);setShipment(op?.supervision?.numero_embarque??"");}
 function changeCount(value:string){const n=Number(value);setCount(n);setSeals((old)=>Array.from({length:n},(_,i)=>old[i]??emptySeal()));}function updateSeal(i:number,patch:Partial<NewSeal>){setSeals((old)=>old.map((x,index)=>index===i?{...x,...patch}:x));}
 function submit(action:"stand_by"|"finalizar"){setMessage(null);setError(null);startTransition(async()=>{try{const form=new FormData();form.set("nombreOperacion",operationName);form.set("numeroEmbarque",shipment);form.set("cantidad",String(count));form.set("instaladorId",installer);form.set("supervisorId",supervisor);form.set("observaciones",notes);form.set("accion",action);seals.forEach((x,i)=>{form.set(`tipo${i}`,x.tipo);form.set(`numero${i}`,x.numero);if(x.foto)form.set(`foto${i}`,x.foto);});if(signatureInstaller)form.set("firmaInstalador",signatureInstaller);if(signatureSupervisor)form.set("firmaSupervisor",signatureSupervisor);const response=await fetch("/api/supervision-sellado",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);setOperationName(action==="stand_by"?operationName:"");setShipment(action==="stand_by"?shipment:"");setCount(1);setSeals([emptySeal()]);setInstaller("");setSupervisor("");setNotes("");setSignatureInstaller(null);setSignatureSupervisor(null);setReset((x)=>x+1);setMessage(action==="stand_by"?"STAND BY guardado. Los datos, fotos y firmas quedan bloqueados y puedes retomarlos desde esta operación.":"Supervisión finalizada. Se conservó el historial de sellados.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible guardar.");}});}
 return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-7xl space-y-7 px-6 py-10"><header className="rounded-[2rem] bg-white p-8 shadow-lg"><div className="flex flex-wrap justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.25em] text-emerald-700">En mantenimiento</span><h1 className="mt-3 text-4xl font-semibold">Supervisión de sellado</h1><p className="mt-3 text-slate-600">Este módulo está en mantenimiento. Por ahora no es obligatorio para registrar la salida en F-SU-04.</p></div><div className="flex gap-3"><button type="button" onClick={()=>setOnlyStandby((x)=>!x)} className="rounded-2xl bg-amber-100 px-5 py-3 text-sm font-semibold text-amber-900">STAND BY pendientes ({operations.filter((x)=>x.supervision?.estado==="stand_by").length})</button><Link href="/" className="h-fit rounded-2xl border px-4 py-3 text-sm font-semibold">Volver</Link></div></div></header>
 <form onSubmit={(e)=>e.preventDefault()} className="space-y-6 rounded-[2rem] border bg-white p-6 shadow-lg md:p-8"><fieldset disabled={pending} className="space-y-6"><SelectField label="Operación pendiente" value={operationName} onChange={choose} options={filtered.map((x)=>({value:x.nombre_operacion,label:`${x.placa} · ${x.fecha}${x.supervision?" · STAND BY":""}`}))} required tone="sky"/><InputField label="Número de embarque" value={shipment} onChange={setShipment} required disabled={Boolean(selected?.supervision)} />
 {events.length ? <div className="space-y-5">{[...events].sort((a,b)=>a.created_at.localeCompare(b.created_at)).map((event,index)=><SavedSelladoEventCard key={event.id} event={event} index={index}/>)}</div> : null}
 <h2 className="text-xl font-semibold">{events.length ? "Continuar con un registro nuevo" : "Datos del sellado"}</h2>
 <SelectField label="Cantidad de precintos nuevos" value={String(count)} onChange={changeCount} options={[1,2,3,4,5].map((x)=>({value:String(x),label:String(x)}))} required tone="sky"/><div className="grid gap-5 md:grid-cols-2">{seals.map((seal,i)=><section key={i} className="space-y-4 rounded-3xl border border-emerald-100 bg-emerald-50/40 p-5"><h3 className="font-semibold">Precinto nuevo {i+1}</h3><SelectField label="Tipo de precinto" value={seal.tipo} onChange={(tipo)=>updateSeal(i,{tipo:tipo as NewSeal["tipo"]})} options={[{value:"correa",label:"Precinto de correa"},{value:"botella",label:"Precinto de botella"}]} required tone="sky"/><InputField label="Número del precinto" value={seal.numero} onChange={(numero)=>updateSeal(i,{numero})} required/><FileField label={`Foto del precinto de ${seal.tipo||"seguridad"}`} file={seal.foto} onChange={(foto)=>updateSeal(i,{foto})} sourceOptions/></section>)}</div>
 <div className="grid gap-4 md:grid-cols-2"><SelectField label="Quién instala los precintos (COLFRUTAS)" value={installer} onChange={setInstaller} options={colfrutas.map((x)=>({value:x.id,label:x.nombre}))} required tone="sky"/><SelectField label="Quién supervisa la instalación (ATEMPI)" value={supervisor} onChange={setSupervisor} options={atempi.map((x)=>({value:x.id,label:x.nombre}))} required tone="sky"/></div><label className="flex flex-col gap-2 text-sm font-medium">Observaciones<textarea rows={3} value={notes} onChange={(e)=>setNotes(e.target.value)} className="rounded-2xl border bg-slate-50 px-4 py-3"/></label><div className="grid gap-5 md:grid-cols-2"><SignaturePad key={`i-${reset}`} label="Firma de quien instala" onChange={setSignatureInstaller}/><SignaturePad key={`s-${reset}`} label="Firma de quien supervisa" onChange={setSignatureSupervisor}/></div><div className="grid gap-4 md:grid-cols-2"><button type="button" disabled={pending || !selected} onClick={()=>submit("finalizar")} className="rounded-2xl bg-slate-950 px-5 py-4 font-bold text-white disabled:bg-slate-400">{pending?"Guardando...":"Guardar y finalizar"}</button><button type="button" disabled={pending || !selected} onClick={()=>submit("stand_by")} className="rounded-2xl bg-amber-500 px-5 py-4 font-bold text-slate-950 disabled:bg-slate-300">{pending?"Guardando...":"STAND BY"}</button></div>{message?<p className="rounded-2xl bg-emerald-50 p-4 text-emerald-800">{message}</p>:null}{error?<p className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p>:null}</fieldset></form></main></div>;
}
